service: spring-cloud-function

custom:
  defaultStage: dev
  defaultRegion: eu-west-1
  defaultVersion: 1.0.0-SNAPSHOT

  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  version: ${opt:version, self:custom.defaultVersion}

  lambdas:
    getWidget:
      name: ${self:custom.stage}-getWidget

    postWidget:
      name: ${self:custom.stage}-postWidget

provider:
  name: aws
  runtime: java8
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  timeout: 15
  environment:
    STAGE: ${self:custom.stage}

package:
  artifact: target/spring-cloud-function-${self:custom.version}-aws.jar

functions:
  getWidget:
    environment:
      FUNCTION_NAME: 'getWidget'
    handler: uk.co.mruoc.CloudHandler
    name: ${self:custom.lambdas.getWidget.name}
    events:
      - http:
          path: widgets/{id}
          method: get

  postWidget:
    environment:
      FUNCTION_NAME: 'postWidget'
    handler: uk.co.mruoc.CloudHandler
    name: ${self:custom.lambdas.postWidget.name}
    events:
      - http:
          path: widgets
          method: post